### ISSUE TITLE
Allow issues to be opened to track bugs and feature requests

### ISSUE THREAD

**Issue by brianreitz** [djhohnstein/ghidorah#1]
The README states the following:

> This project is not under active development and as such will not be supported like it is. All issues will be closed.

Many open-source projects use issues as a way to track problems that users encounter when using or developing the project, and to get feedback on features and use cases that would be an improvement to the project. 

![image](https://user-images.githubusercontent.com/17878883/57629140-47e95280-7569-11e9-9310-d887a62e14cd.png)

Also, here is a puppy. You wouldn't close a puppy, would you?

**Comment by djhohnstein** [comment]
Closed for being off-topic and against the rules of this sub.
